config/routes.rb
Rails.application.routes.draw do


  get 'classifica_c/table'
  get 'classifica/table'
  devise_for :users , controllers: {registrations: 'users/registrations'}, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

    #da capire se da errore
    resources :users, only: [:show, :edit, :update]

  resources :profile

  as :user do
    get 'profile', :to => 'profile#index', :as => :user_root # Rails 3
  end

  root 'static_pages#home'
  get 'regolamento'    => 'static_pages#regolamento'
  get 'infoclan'    => 'static_pages#infoclan'
  get 'aboutapp'    => 'static_pages#aboutapp'
  get 'contatti'    => 'static_pages#contatti'
  get 'classifica' => 'classifica#table'
  get 'classifica_c' => 'classifica_c#table'
end

app/views/layouts/_footer.html.erb
<% if user_signed_in? %>
<footer class="footer">



<small> War-Rails </small>

<nav>

<ul>

<li><%= link_to "AboutApp", aboutapp_path %></li>
 <li><%= link_to "Contatti", contatti_path %></li>

 </ul>

 </nav>

 <% end %>

 </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <% if user_signed_in? %>

  <nav>
      <ul class="nav navbar-nav pull-left">
     <li><%= link_to "COMBATTI", '#' %></li>
     <li><%= link_to "PROFILO", profile_path(current_user.id) %></li>
        <li><%= link_to "REGOLAMENTO",   regolamento_path %></li>

    <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            CLASSIFICHE<b class="caret"></b>
    </a>
        <ul class="dropdown-menu">
        <li><%= link_to "Classifica Generale", classifica_path %></li>
        <li><%= link_to "Classifica Membri Clan", classifica_c_path %> </li>
        </ul>
    </li>



            <li><%= link_to "INFOCLAN",   infoclan_path %></li>
      </ul>

      <ul class ="nav navbar-nav navbar-right">
        <li><%= link_to 'LOGOUT', destroy_user_session_path, :method => :delete%></li>
        </ul>
    </nav>


  <% else %>
    <%= link_to "War-Rails", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-left">
        <li><%= link_to "REGOLAMENTO",   regolamento_path %></li>
            <li><%= link_to "INFOCLAN",   infoclan_path %></li>
            <li><%= link_to "ABOUTAPP", aboutapp_path %></li>
            <li><%= link_to "CONTATTI", contatti_path %></li>
      </ul>
      <ul class ="nav navbar-nav navbar-right">
        <li><a href=register><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
    <li><a href=login><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </nav>

<% end %>

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
    <%= yield %>

    <% if user_signed_in? %>
        <br>
        <br>
    <% end %>

      <%= render 'layouts/footer' %>

    </div>


  </body>
</html>